  version: '2'

  services:

    #PHP Service
    phps:
      container_name: phps
      build:
        context: .
        dockerfile: Dockerfile-php
      working_dir: /var/www/laravel
      restart: unless-stopped
      ports:
        - "9001:9000"
      volumes:
        - ./:/var/www/laravel
      networks:
        - app-network

    #Nginx Service
    webserv:
      container_name: webserv
      image: nginx:latest
      working_dir: /var/www/laravel
      restart: unless-stopped
      ports:
        - "9081:80"
        - "4431:443"
      volumes:
        - ./:/var/www/laravel
        - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./docker/nginx/log/:/var/log/nginx/
      networks:
        - app-network

    #MySQL Service
    dbs:
      container_name: dbs
      image: mysql:5.7
      restart: unless-stopped
      ports:
        - "3308:3306"
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: laravel
      networks:
        - app-network


  #Docker Networks
  networks:
    app-network:
      driver: bridge




